name: .NET CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: NuGet cache
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore
        run: dotnet restore ConsoleApp1/ConsoleApp1.csproj

      - name: Build
        run: dotnet build ConsoleApp1/ConsoleApp1.csproj --configuration Release --no-restore

      - name: Check formatting (non-blocking)
        continue-on-error: true
        run: |
          dotnet tool install -g dotnet-format
          echo "##[group]dotnet-format"
          ~/.dotnet/tools/dotnet-format ConsoleApp1/ConsoleApp1.csproj --no-restore --verify-no-changes || echo "Formatting differences detected. Run 'dotnet format' locally."
          echo "##[endgroup]"
