name: Auto Format (dotnet-format)

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install dotnet-format
        run: dotnet tool install -g dotnet-format

      - name: Run formatter
        run: |
          ~/.dotnet/tools/dotnet-format ConsoleApp1/ConsoleApp1.csproj --verbosity minimal || true

      - name: Commit changes if any
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "style: apply dotnet-format"
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          branch: ${{ github.head_ref }}

